name:                homework01
version:             0.1.0.0

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Widentities
- -Wredundant-constraints
- -O2

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  homework01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework01
    - hspec
    - QuickCheck
    - generic-random
    - containers
    - process
    - extra
    - bytestring
