name:                homework00
version:             0.1.0.0

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Widentities
- -Wredundant-constraints

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  homework00-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homework00
    - hspec
    - QuickCheck
    - generic-random

flags:
  can:
    description: Run Can.hs tests
    manual: true
    default: false


when:
- condition: flag(can)
  cpp-options: -DCAN
